# baseURL = "https://kirontoo.github.io/"
baseUrl = "https://blog.rxkiro.xyz/"
theme = "terminal"
title = "kironto"
author = "Amy Dang"
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# google analytics
googleAnalytics = 'G-X88TJR147W'

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"
enableRobotsTXT = true

[params]
# ---------- TERMINAL
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  readingTime = true # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = true # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  cactusCommentsSiteName = "blog.rxkiro.xyz"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "rxkironto"
  site = "rxkironto"

[languages]
  [languages.en]
    title = "Kironto"
    subtitle = "kiront's blog"
    keywords = "blog, kironto, amy dang, dev, webdev, linux, react, svelte, typescript, javascript, web development, neovim"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "I think you're lost."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "[kironto] $"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "whoami"
        name = "whoami"
        url = "/whoami"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "contact"
        url = "/contact"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"

      [[languages.en.menu.main]]
        identifier = "series"
        name = "series"
        url = "/series/"

      [[languages.en.menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true
